import { QueryClient } from '@tanstack/react-query';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import '@radix-ui/themes/styles.css';

const inter = Inter({ subsets: ['latin'] })

// This is the sample change
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {

    const queryClient = new QueryClient();

  return (
    <html lang="en" data-theme="cupcake">
      
        <body className={inter.className}>{children}</body>
      
    </html>
  )
}
